"""Added new Enrollments Table

Revision ID: 726b056753e9
Revises: 3600e26e46b3
Create Date: 2023-11-20 14:37:37.153430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726b056753e9'
down_revision = '3600e26e46b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course_table.id'], name=op.f('fk_enrollment_table_course_id_course_table')),
    sa.ForeignKeyConstraint(['student_id'], ['student_table.id'], name=op.f('fk_enrollment_table_student_id_student_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollment_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_table')
    # ### end Alembic commands ###
